#ifndef TRF797X_CONF_H
#define TRF797X_CONF_H

#include <trfconf.h>

#define CLEAR(PAD)                      palClearPad(TRF797X_CFG_GPIO_PORT_ ## PAD, TRF797X_CFG_GPIO_PIN_ ## PAD)
#define SET(PAD)                        palSetPad(TRF797X_CFG_GPIO_PORT_ ## PAD, TRF797X_CFG_GPIO_PIN_ ## PAD)
#define READ(PAD)                       palReadPad(TRF797X_CFG_GPIO_PORT_ ## PAD, TRF797X_CFG_GPIO_PIN_ ## PAD)

#ifndef TRF797X_CFG_OSCILLATOR_27MHZ
#warning "TRF797X_CFG_OSCILLATOR_27MHZ not defined, default to FALSE."
#define TRF797X_CFG_OSCILLATOR_27MHZ        FALSE
#endif

#ifndef TRF797X_CFG_SYS_CLK_DIVIDER
#warning "TRF797X_CFG_SYS_CLK_DIVIDER not defined, default to 0."
#define TRF797X_CFG_SYS_CLK_DIVIDER         0
#endif

#if TRF797X_CFG_SYS_CLK_DIVIDER < 0
#error "TRF797X_CFG_SYS_CLK_DIVIDER must be greater or equals to 0"
#elif TRF797X_CFG_SYS_CLK_DIVIDER > 4
#error "TRF797X_CFG_SYS_CLK_DIVIDER must be less or equals to 4"
#endif

#if !defined(TRF797X_CFG_GPIO_PORT_EN) || !defined(TRF797X_CFG_GPIO_PIN_EN)
#error "TRF797X_CFG_GPIO_PORT_EN and TRF797X_CFG_GPIO_PIN_EN are required."
#endif

#if defined(TRF797X_CFG_GPIO_PORT_EN2) && defined(TRF797X_CFG_GPIO_PIN_EN2)
#define TRF797X_USE_EN2     TRUE
#else
#define TRF797X_USE_EN2     FALSE
#endif

#if defined(TRF797X_CFG_GPIO_PORT_IO0) && defined(TRF797X_CFG_GPIO_PIN_IO0)
#define TRF797X_USE_IO0     TRUE
#else
#define TRF797X_USE_IO0     FALSE
#endif

#if defined(TRF797X_CFG_GPIO_PORT_IO1) && defined(TRF797X_CFG_GPIO_PIN_IO1)
#define TRF797X_USE_IO1     TRUE
#else
#define TRF797X_USE_IO1     FALSE
#endif

#if defined(TRF797X_CFG_GPIO_PORT_IO2) && defined(TRF797X_CFG_GPIO_PIN_IO2)
#define TRF797X_USE_IO2     TRUE
#else
#define TRF797X_USE_IO2     FALSE
#endif

#if defined(TRF797X_CFG_GPIO_PORT_IO4) && defined(TRF797X_CFG_GPIO_PIN_IO4)
#define TRF797X_CFG_GPIO_PORT_CS           TRF797X_CFG_GPIO_PORT_IO4
#define TRF797X_CFG_GPIO_PIN_CS            TRF797X_CFG_GPIO_PIN_IO4
#else
#error "TRF797X_CFG_GPIO_PORT_IO4 and TRF797X_CFG_GPIO_PIN_IO4 are required."
#endif

#define TRF797X_CFG_GPIO_PORT_DM1_CLK      TRF797X_CFG_GPIO_PORT_IO5
#define TRF797X_CFG_GPIO_PIN_DM1_CLK       TRF797X_CFG_GPIO_PIN_IO5

#define TRF797X_CFG_GPIO_PORT_SDM_CLK      TRF797X_CFG_GPIO_PORT_DM1_CLK
#define TRF797X_CFG_GPIO_PIN_SDM_CLK       TRF797X_CFG_GPIO_PIN_DM1_CLK

#define TRF797X_CFG_GPIO_PORT_DM0_DATA_IN  TRF797X_CFG_GPIO_PORT_MOD
#define TRF797X_CFG_GPIO_PIN_DM0_DATA_IN   TRF797X_CFG_GPIO_PIN_MOD

#define TRF797X_CFG_GPIO_PORT_DM1_DATA_IN  TRF797X_CFG_GPIO_PORT_DM0_DATA_IN
#define TRF797X_CFG_GPIO_PIN_DM1_DATA_IN   TRF797X_CFG_GPIO_PIN_DM0_DATA_IN

#endif // TRF797X_CONF_H