#include <hal.h>

#define CONFIGURE_PAD(NAME)    gpioSetPadMode(NAME, NAME ## _MODE)

void __early_init(void) {

  stm32_clock_init();
}

/**
 * @brief   Board-specific initialization code.
 */
void boardInit(void) {

  gpioInit();

  // TRF7970A
  gpioClearPad(GPIO_EN);

  CONFIGURE_PAD(GPIO_IRQ);
  CONFIGURE_PAD(GPIO_EN);
  CONFIGURE_PAD(GPIO_EN2);
  CONFIGURE_PAD(GPIO_IO0);
  CONFIGURE_PAD(GPIO_IO1);
  CONFIGURE_PAD(GPIO_DM_CLK);
  CONFIGURE_PAD(GPIO_ASK_OOK);
  CONFIGURE_PAD(GPIO_SDM_TX_EN);
  CONFIGURE_PAD(GPIO_MOD);
  CONFIGURE_PAD(GPIO_DM_DATA_OUT);
  CONFIGURE_PAD(GPIO_SDM_TX);

  // SPI1
  CONFIGURE_PAD(GPIO_SPI1_SCK);
  CONFIGURE_PAD(GPIO_SPI_MISO);
  CONFIGURE_PAD(GPIO_SPI_MOSI);
  CONFIGURE_PAD(GPIO_CS);

  // UART
  CONFIGURE_PAD(GPIO_UART_TX);
  CONFIGURE_PAD(GPIO_UART_RX);

  // USB
  CONFIGURE_PAD(GPIO_OTG_FS_DM);
  CONFIGURE_PAD(GPIO_OTG_FS_DP);

  // MISC
  CONFIGURE_PAD(GPIO_LED0);
  CONFIGURE_PAD(GPIO_LED1);
  CONFIGURE_PAD(GPIO_BUTTON);
}
